"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# "~/config"までの絶対パスを取得
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # "__file__"はカレントディレクトリからの相対パス

SECRET_KEY = '(ojzv#@f9v!1obpxjcp-9a74e(9wii__y71^t+tjbcnh(@3@4k'

DEBUG = True

ALLOWED_HOSTS = ['*']


# アプリケーション
INSTALLED_APPS = [
    'polls',
    'blog',
    'django.contrib.admin',  # adminサイト
    'django.contrib.auth',  # 認証機能
    'django.contrib.contenttypes',  # コンテンツタイプフレームワーク
    'django.contrib.sessions',  # セッションフレームワーク
    'django.contrib.messages',  # メッセージフレームワーク
    'django.contrib.staticfiles',  # staticファイルの使用に必要
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ルートとなるurls.pyを指定
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # templatesディレクトリを指定する
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# config/wsgi.pyを読み込む
WSGI_APPLICATION = 'config.wsgi.application'


# Password バリデーション
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# webサーバが参考にするURL(webサーバのドキュメントルートに配置)
STATIC_URL = "/static/"

# collectstaticコマンドで集約されるディレクトリを指定
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
